version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: chatbotdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./api/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db

  bot:
    build: ./bot
    ports:
      - "3978:3978"
    depends_on:
      - api

volumes:
  db_data:
